// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJIJF6qPTo5hi8jfAcS2v8wmaDORajR0I',
    appId: '1:483730233887:web:abd074704201e40e2cd32a',
    messagingSenderId: '483730233887',
    projectId: 'fir-project-819d1',
    authDomain: 'fir-project-819d1.firebaseapp.com',
    storageBucket: 'fir-project-819d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwnYRSnWw8Uaq9UP3Cxacldyv9jzR4_Q',
    appId: '1:483730233887:android:683ecf9e50b870b82cd32a',
    messagingSenderId: '483730233887',
    projectId: 'fir-project-819d1',
    storageBucket: 'fir-project-819d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jdxVOJbbMXxvJfIwxy3oTexnss7hQgI',
    appId: '1:483730233887:ios:ec70b325a3642eff2cd32a',
    messagingSenderId: '483730233887',
    projectId: 'fir-project-819d1',
    storageBucket: 'fir-project-819d1.appspot.com',
    iosClientId: '483730233887-0jvkla7qfe2q851r45p50q27t432kv07.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jdxVOJbbMXxvJfIwxy3oTexnss7hQgI',
    appId: '1:483730233887:ios:49193dd37174b0d52cd32a',
    messagingSenderId: '483730233887',
    projectId: 'fir-project-819d1',
    storageBucket: 'fir-project-819d1.appspot.com',
    iosClientId: '483730233887-i03gvpdbi2cqho58mjq7ddee7uuuqn17.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralApp.RunnerTests',
  );
}
